import { IEleccion } from "../interfaces/actas.interfaces";

export const ID_ELECCION: IEleccion = {
  ID_ELECCION_MUNICIPAL: 4,
  ID_ELECCION_GENERAL: 5,
  ID_ELECCION_PRESIDENCIAL: 10,
  ID_ELECCION_DIPUTADOS: 13,
  ID_ELECCION_PARLAMENTO_ANDINO: 12,
  ID_ELECCION_SENADOR_27: 14,
  ID_ELECCION_SENADOR_33: 15,
  ID_ELECCION_REVOCATORIA: 7,
};
