/**
 * CAMBIAR ESTE VALOR SEGÚN SE NECESITE PINTAR EL MAPA (VALOR DE PRODUCCIÓN DEBE SER 1)
 */
// export const MULTIPLIER_HOT_MAP = 500;
export const MULTIPLIER_HOT_MAP = 1;
export const MULTIPLIER_HOT_MAP_REVOCA = 1;

/**
 * CAMBIAR ESTE VALOR SEGÚN SE NECESITE PINTAR EL MAPA (VALOR DE PRODUCCIÓN DEBE SER 1)
 */
export const MULTIPLIER_PERCENTAGE_VALID_VOTES = 1;

export const LEGEND_HEIGHT = 55;
