
server.port=8080
server.servlet.context-path=${APPLICATION_ROOT_COP}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#spring.data.mongodb.uri=mongodb://${MONGO_USER}:${MONGO_PASS}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB}

# Base de datos primaria
spring.data.mongodb.primary.uri = mongodb://${MONGO_USER_P}:${MONGO_PASS_P}@${MONGO_HOST_P}:${MONGO_PORT_P}?authSource=${MONGO_DB_SOURCE}&replicaSet=rs0&tls=true
spring.data.mongodb.primary.database = ${MONGO_DB_P}

# Base de datos secundaria
spring.data.mongodb.secondary.uri = mongodb://${MONGO_USER_S}:${MONGO_PASS_S}@${MONGO_HOST_S}:${MONGO_PORT_S}?authSource=${MONGO_DB_SOURCE}&replicaSet=rs0&tls=true
spring.data.mongodb.secondary.database = ${MONGO_DB_S}

cop.nfs.path=${COP_NFS_PATH}
cop.nfs.files=${COP_NFS_FILES}

# Procesamiento de Actas (Nuevo)
pr.nfs.actas.origen=${PR_NFS_ACTAS_ORIGEN}
pr.nfs.actas.destino=${PR_NFS_ACTAS_DESTINO}

logging.level.root=INFO
logging.level.pe.gob.onpe.consultaopbackend=INFO
logging.level.org.springframework.data.mongodb.core.MongoTemplate=INFO
logging.level.org.springframework.aop.interceptor.AsyncExecutionInterceptor=DEBUG

sasa.url=${SASA_URL}
sasa.codigo=MOD_ESP_PR

security.jwt.tokenExpirationTime=300
security.jwt.refreshTokenExpTime=600
security.jwt.tokenIssuer=ONPE
security.jwt.tokenSigningKey=${JWT_SECRET}

recaptcha.siteKey=${RECAPTCHA_SITE_KEY}
recaptcha.secretKey=${RECAPTCHA_SECRET_KEY}
recaptcha.threshold=${RECAPTCHA_THRESHOLD}
recaptcha.validar=${RECAPTCHA_VALIDAR}
seguridad.validar=${SEGURIDAD_VALIDAR}
crossorigin.habilitado=${CROSSORIGIN_HABILITADO}
crossorigin.urls=${URL_ESPECIALIZADO}

public.key=${PUBLIC_KEY}
private.key=${PRIVATE_KEY}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.database=0
spring.data.redis.ssl.enabled=${REDIS_SSL_ENABLED}
spring.data.redis.timeout=${REDIS_TIMEOUT}

##CONSULTA OP BACKEND EXCEL
app.consulta.backend = ${COP_BACKEND_EXCEL}

# ======================================
# AWS S3 CONFIG
# ======================================

aws.region=${AWS_REGION}
aws.bucket-name=${AWS_BUCKET_NAME}
aws.s3.key-reportes-prefix=${AWS_S3_KEY_REPORTES_PREFIX}
despliegue-nube=${DESPLIEGUE_NUBE}

aws.bucket-actas-name=${AWS_BUCKET_ACTAS_NAME}
aws.s3.key-actas-prefix=${AWS_S3_KEY_ACTAS_PREFIX}
