# =========================
# SONARCLOUD CONFIG
# =========================

sonar.projectKey=kennethortega-myt_RetestPR
sonar.organization=kennethortega-myt

sonar.sourceEncoding=UTF-8

# Analizar solo código fuente
sonar.sources=.

# Excluir basura pesada
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.png,**/*.jpg,**/*.pdf,**/*.zip,**/*.exe,**/*.dll,**/*.log

# Lenguajes principales detectados
sonar.inclusions=**/*.js,**/*.ts,**/*.java,**/*.html,**/*.css,**/*.xml