server.port=8080
server.servlet.context-path=${APPLICATION_ROOT}
server.error.whitelabel.enabled=false
spring.servlet.multipart.max-file-size=8MB
spring.servlet.multipart.max-request-size=8MB

# spring.data.mongodb.uri=mongodb://${MONGO_USER}:${MONGO_PASS}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB}?authSource=${MONGO_DB_SOURCE}
# Base de datos primaria
spring.data.mongodb.primary.uri = mongodb://${MONGO_USER_P}:${MONGO_PASS_P}@${MONGO_HOST_P}:${MONGO_PORT_P}?authSource=${MONGO_DB_SOURCE}&replicaSet=rs0&tls=true
spring.data.mongodb.primary.database = ${MONGO_DB_P}

# Base de datos secundaria
spring.data.mongodb.secondary.uri = mongodb://${MONGO_USER_S}:${MONGO_PASS_S}@${MONGO_HOST_S}:${MONGO_PORT_S}?authSource=${MONGO_DB_SOURCE}&replicaSet=rs0&tls=true
spring.data.mongodb.secondary.database = ${MONGO_DB_S}

springdoc.api-docs.enabled = true
springdoc.swagger-ui.enabled = true
springdoc.swagger-ui.path = /swagger-ui.html
application.title = Presentacion de resultados
application.version = 2.4.0

pr.nfs.path=${PR_NFS_PATH}
pr.nfs.files=${PR_NFS_FILES}

spring.data.redis.database=0
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.ssl.enabled=${REDIS_SSL_ENABLED}
spring.data.redis.timeout=${REDIS_TIMEOUT}

logging.level.root=ERROR
logging.level.pe.gob.onpe.presentacionbackend=ERROR
logging.level.org.springframework.data.mongodb.core.MongoTemplate=ERROR
