package pe.gob.onpe.pradminbackend.utils;

import java.util.Map;

public class UbigeoConTildeUtil {

    private UbigeoConTildeUtil() { }

    private static final Map<String, String> nombresConTilde = Map.<String, String>ofEntries(
        Map.entry("BOQUERON", "BOQUERÓN"),
        Map.entry("APURIMAC", "APURÍMAC"),
        Map.entry("JUNIN", "JUNÍN"),
        Map.entry("HUAMALI", "HUAMALÍ"),
        Map.entry("ANCASH", "ÁNCASH"),
        Map.entry("HUANUCO", "HUÁNUCO"),
        Map.entry("SAN MARTIN", "SAN MARTÍN"),
        Map.entry("AFRICA", "ÁFRICA"),
        Map.entry("AMERICA", "AMÉRICA"),
        Map.entry("OCEANIA", "OCEANÍA"),
        Map.entry("ASUNCION", "ASUNCIÓN"),
        Map.entry("SAN JERONIMO", "SAN JERÓNIMO"),
        Map.entry("SANTO TOMAS", "SANTO TOMÁS"),
        Map.entry("SAN NICOLAS", "SAN NICOLÁS"),
        Map.entry("RIO SANTIAGO", "RÍO SANTIAGO"),
        Map.entry("CACERES DEL PERU", "CACERES DEL PERÚ"),
        Map.entry("JOSE MARIA ARGUEDAS", "JOSÉ MARIA ARGUEDAS"),
        Map.entry("JOSE LUIS BUSTAMANTE Y RIVERO", "JOSÉ LUIS BUSTAMANTE Y RIVERO"),
        Map.entry("JOSE MARIA QUIMPER", "JOSÉ MARIA QUIMPER"),
        Map.entry("MARIANO NICOLAS VALCARCEL", "MARIANO NICOLÁS VALCARCEL"),
        Map.entry("NICOLAS DE PIEROLA", "NICOLÁS DE PIEROLA"),
        Map.entry("BELLA UNION", "BELLA UNIÓN"),
        Map.entry("RIO GRANDE", "RÍO GRANDE"),
        Map.entry("MEJIA", "MEJÍA"),
        Map.entry("LA UNION", "LA UNIÓN"),
        Map.entry("SAN JOSE DE TICLLAS", "SAN JOSÉ DE TICLLAS"),
        Map.entry("JESUS NAZARENO", "JESÚS NAZARENO"),
        Map.entry("UNION PROGRESO", "UNIÓN PROGRESO"),
        Map.entry("RIO MAGDALENA", "RÍO MAGDALENA"),
        Map.entry("CONCEPCION", "CONCEPCIÓN"),
        Map.entry("SAN JOSE DE USHUA", "SAN JOSÉ DE USHUA"),
        Map.entry("BELEN", "BELÉN"),
        Map.entry("JESUS", "JESÚS"),
        Map.entry("CELENDIN", "CELENDÍN"),
        Map.entry("JORGE CHAVEZ", "JORGE CHÁVEZ"),
        Map.entry("JOSE GALVEZ", "JOSÉ GÁLVEZ"),
        Map.entry("SAN ANDRES DE CUTERVO", "SAN ANDRÉS DE CUTERVO"),
        Map.entry("SAN JOSE DEL ALTO", "SAN JOSÉ DEL ALTO"),
        Map.entry("UNION AGUA BLANCA", "UNIÓN AGUA BLANCA"),
        Map.entry("SAN JOSE DE LOURDES", "SAN JOSÉ DE LOURDES"),
        Map.entry("PEDRO GALVEZ", "PEDRO GÁLVEZ"),
        Map.entry("JOSE SABOGAL", "JOSÉ SABOGAL"),
        Map.entry("UNION ASHÁNINKA", "UNIÓN ASHÁNINKA"),
        Map.entry("SANTO TOMAS DE PATA", "SANTO TOMÁS DE PATA"),
        Map.entry("JOSE CRESPO Y CASTILLO", "JOSÉ CRESPO Y CASTILLO"),
        Map.entry("SAN JOSE DE LOS MOLINOS", "SAN JOSÉ DE LOS MOLINOS"),
        Map.entry("SAN ANDRES", "SAN ANDRÉS"),
        Map.entry("SAN AGUSTIN", "SAN AGUSTÍN"),
        Map.entry("SAN JOSE DE QUERO", "SAN JOSÉ DE QUERO"),
        Map.entry("RIO NEGRO", "RÍO NEGRO"),
        Map.entry("RIO TAMBO", "RÍO TAMBO"),
        Map.entry("SAN RAMON", "SAN RAMÓN"),
        Map.entry("SANCHEZ CARRION", "SÁNCHEZ CARRIÓN"),
        Map.entry("SAN JOSE", "SAN JOSÉ"),
        Map.entry("JOSE LEONARDO ORTIZ", "JOSÉ LEONARDO ORTIZ"),
        Map.entry("SAN MARTIN DE PORRES", "SAN MARTÍN DE PORRES"),
        Map.entry("SAN ANDRES DE TUPICOCHA", "SAN ANDRÉS DE TUPICOCHA"),
        Map.entry("TOMAS", "TOMÁS"),
        Map.entry("OYON", "OYÓN"),
        Map.entry("EMILIO SAN MARTIN", "EMILIO SAN MARTÍN"),
        Map.entry("MARISCAL RAMON CASTILLA", "MARISCAL RAMÓN CASTILLA"),
        Map.entry("RAMON CASTILLA", "RAMÓN CASTILLA"),
        Map.entry("MANU", "MANÚ"),
        Map.entry("GENERAL SANCHEZ CERRO", "GENERAL SÁNCHEZ CERRO"),
        Map.entry("DANIEL ALCIDES CARRION", "DANIEL ALCIDES CARRIÓN"),
        Map.entry("BELLAVISTA DE LA UNION", "BELLAVISTA DE LA UNIÓN"),
        Map.entry("JOSE DOMINGO CHOQUEHUANCA", "JOSÉ DOMINGO CHOQUEHUANCA"),
        Map.entry("SAN JOSE DE SISA", "SAN JOSÉ DE SISA"),
        Map.entry("MI PERU", "MI PERÚ"),
        Map.entry("RIO BRANCO", "RÍO BRANCO"),
        Map.entry("REPUBLICA ARABE DE EGIPTO", "REPÚBLICA ÁRABE DE EGIPTO"),
        Map.entry("SUDAFRICA", "SUDÁFRICA"),
        Map.entry("CANADA", "CANADÁ"),
        Map.entry("ESTADOS UNIDOS DE AMERICA", "ESTADOS UNIDOS DE ÁMERICA"),
        Map.entry("HAITI", "HAITÍ"),
        Map.entry("MEXICO", "MÉXICO"),
        Map.entry("PANAMA", "PANAMÁ"),
        Map.entry("REPUBLICA DOMINICANA", "REPÚBLICA DOMINICANA"),
        Map.entry("EMIRATOS ARABES UNIDOS", "EMIRATOS ÁRABES UNIDOS"),
        Map.entry("IRAN", "IRÁN"),
        Map.entry("JAPON", "JAPÓN"),
        Map.entry("LIBANO", "LÍBANO"),
        Map.entry("REPUBLICA DEL COREA DEL SUR", "REPÚBLICA DEL COREA DEL SUR"),
        Map.entry("REPUBLICA POPULAR CHINA", "REPÚBLICA POPULAR CHINA"),
        Map.entry("TURQUIA", "TURQUÍA"),
        Map.entry("BELGICA", "BÉLGICA"),
        Map.entry("PAISES BAJOS", "PAÍSES BAJOS"),
        Map.entry("HUNGRIA", "HUNGRÍA"),
        Map.entry("REPUBLICA CHECA", "REPÚBLICA CHECA"),
        Map.entry("RUMANIA", "RUMANÍA"),
        Map.entry("CORDOBA", "CÓRDOBA"),
        Map.entry("GOIAS", "GOIÁS"),
        Map.entry("COPIAPO", "COPIAPÓ"),
        Map.entry("BOGOTA", "BOGOTÁ"),
        Map.entry("MEDELLIN", "MEDELLÍN"),
        Map.entry("LOS ANGELES", "LOS ÁNGELES"),
        Map.entry("PUERTO PRINCIPE", "PUERTO PRÍNCIPE"),
        Map.entry("CIUDAD DE MEXICO", "CIUDAD DE MÉXICO"),
        Map.entry("DUBAI", "DUBÁI"),
        Map.entry("SEUL", "SEÚL"),
        Map.entry("SHANGHAI", "SHANGHÁI"),
        Map.entry("HANOI", "HANÓI"),
        Map.entry("BERLIN", "BERLÍN"),
        Map.entry("MUNICH", "MÚNICH"),
        Map.entry("ALMERIA", "ALMERÍA"),
        Map.entry("MALAGA", "MÁLAGA"),
        Map.entry("PARIS", "PARÍS"),
        Map.entry("SALONICA", "SALÓNICA"),
        Map.entry("AMSTERDAM", "ÁMSTERDAM"),
        Map.entry("DUBLIN", "DUBLÍN"),
        Map.entry("GENOVA", "GÉNOVA"),
        Map.entry("MILAN", "MILÁN"),
        Map.entry("NAPOLES", "NÁPOLES"),
        Map.entry("TURIN", "TURÍN"),
        Map.entry("MOSCU", "MOSCÚ"),
        Map.entry("ZURICH", "ZÚRICH"),
        Map.entry("SIDNEY", "SÍDNEY"),
        Map.entry("BONGARA", "BONGARÁ"),
        Map.entry("RODRIGUEZ DE MENDOZA", "RODRÍGUEZ DE MENDOZA"),
        Map.entry("CARLOS FERMIN FITZCARRALD", "CARLOS FERMÍN FITZCARRALD"),
        Map.entry("CAMANA", "CAMANÁ"),
        Map.entry("CARAVELI", "CARAVELÍ"),
        Map.entry("PAUCAR DEL SARA SARA", "PÁUCAR DEL SARA SARA"),
        Map.entry("VICTOR FAJARDO", "VÍCTOR FAJARDO"),
        Map.entry("VILCAS HUAMAN", "VILCAS HUAMÁN"),
        Map.entry("JAEN", "JAÉN"),
        Map.entry("LA CONVENCION", "LA CONVENCIÓN"),
        Map.entry("MARAÑON", "MARAÑÓN"),
        Map.entry("BOLIVAR", "BOLÍVAR"),
        Map.entry("CHEPEN", "CHEPÉN"),
        Map.entry("GRAN CHIMU", "GRAN CHIMÚ"),
        Map.entry("JULCAN", "JULCÁN"),
        Map.entry("VIRU", "VIRÚ"),
        Map.entry("HUAROCHIRI", "HUAROCHIRÍ"),
        Map.entry("DATEM DEL MARAÑON", "DATEM DEL MARAÑÓN"),
        Map.entry("MORROPON", "MORROPÓN"),
        Map.entry("HUANCANE", "HUANCANÉ"),
        Map.entry("SAN ROMAN", "SAN ROMÁN"),
        Map.entry("MARISCAL CACERES", "MARISCAL CÁCERES"),
        Map.entry("MARIA", "MARÍA"),
        Map.entry("SAN CRISTOBAL", "SAN CRISTÓBAL"),
        Map.entry("CHAVIN DE HUANTAR", "CHAVÍN DE HUÁNTAR"),
        Map.entry("ELEAZAR GUZMAN BARRON", "ELEAZAR GUZMÁN BARRÓN"),
        Map.entry("SAN CRISTOBAL DE RAJAN", "SAN CRISTÓBAL DE RAJAN"),
        Map.entry("CACERES DEL PERÚ", "CÁCERES DEL PERÚ"),
        Map.entry("SANTA MARIA DE CHICMO", "SANTA MARÍA DE CHICMO"),
        Map.entry("DEAN VALDIVIA", "DEÁN VALDIVIA"),
        Map.entry("PUNTA DE BOMBON", "PUNTA DE BOMBÓN"),
        Map.entry("MARIA PARADO DE BELLIDO", "MARÍA PARADO DE BELLIDO"),
        Map.entry("ANDRES AVELINO CACERES DORREGARAY", "ANDRÉS AVELINO CÁCERES DORREGARAY"),
        Map.entry("SANTA LUCIA", "SANTA LUCÍA"),
        Map.entry("HUASMIN", "HUASMÍN"),
        Map.entry("LA LIBERTAD DE PALLAN", "LA LIBERTAD DE PALLÁN"),
        Map.entry("ANGUIA", "ANGUÍA"),
        Map.entry("CHADIN", "CHADÍN"),
        Map.entry("CHIMBAN", "CHIMBÁN"),
        Map.entry("CONCHAN", "CONCHÁN"),
        Map.entry("PION", "PIÓN"),
        Map.entry("YONAN", "YONÁN"),
        Map.entry("CHONTALI", "CHONTALÍ"),
        Map.entry("ICHOCAN", "ICHOCÁN"),
        Map.entry("JOSE MANUEL QUIROZ", "JOSÉ MANUEL QUIRÓZ"),
        Map.entry("TUMBADEN", "TUMBADÉN"),
        Map.entry("PULAN", "PULÁN"),
        Map.entry("TUPAC AMARU", "TÚPAC AMARU"),
        Map.entry("SAN SEBASTIAN", "SAN SEBASTIÁN"),
        Map.entry("ASCENSION", "ASCENSIÓN"),
        Map.entry("CORDOVA", "CÓRDOVA"),
        Map.entry("DANIEL HERNÁNDEZ", "DANIEL HERNÁNDEZ"),
        Map.entry("MARIAS", "MARÍAS"),
        Map.entry("RIPAN", "RIPÁN"),
        Map.entry("CHAVIN DE PARIARCA", "CHAVÍN DE PARIARCA"),
        Map.entry("JIRCAN", "JIRCÁN"),
        Map.entry("MONZON", "MONZÓN"),
        Map.entry("SAN FRANCISCO DE CAYRAN", "SAN FRANCISCO DE CAYRÁN"),
        Map.entry("SAN PEDRO DE CHAULAN", "SAN PEDRO DE CHAULÁN"),
        Map.entry("SANTA MARIA DEL VALLE", "SANTA MARÍA DEL VALLE"),
        Map.entry("SAN FRANCISCO DE ASIS", "SAN FRANCISCO DE ASÍS"),
        Map.entry("DANIEL ALOMIA ROBLES", "DANIEL ALOMÍA ROBLES"),
        Map.entry("HERMILIO VALDIZAN", "HERMILIO VALDIZÁN"),
        Map.entry("MARIANO DAMASO BERAUN", "MARIANO DÁMASO BERAÚN"),
        Map.entry("CHOLON", "CHOLÓN"),
        Map.entry("CHAVIN", "CHAVÍN"),
        Map.entry("PERENE", "PERENÉ"),
        Map.entry("HEROINAS TOLEDO", "HEROÍNAS TOLEDO"),
        Map.entry("SAN JERONIMO DE TUNAN", "SAN JERÓNIMO DE TUNÁN"),
        Map.entry("VIZCATAN DEL ENE", "VIZCATÁN DEL ENE"),
        Map.entry("SANTA BARBARA DE CARHUACAYAN", "SANTA BÁRBARA DE CARHUACAYÁN"),
        Map.entry("PAIJAN", "PAIJÁN"),
        Map.entry("RAZURI", "RÁZURI"),
        Map.entry("PIAS", "PIÁS"),
        Map.entry("SANAGORAN", "SANAGORÁN"),
        Map.entry("SARIN", "SARÍN"),
        Map.entry("VICTOR LARCO HERRERA", "VÍCTOR LARCO HERRERA"),
        Map.entry("CAYALTI", "CAYALTÍ"),
        Map.entry("MONSEFU", "MONSEFÚ"),
        Map.entry("OYOTUN", "OYOTÚN"),
        Map.entry("PATAPO", "PATAPÓ"),
        Map.entry("PICSI", "PICSÍ"),
        Map.entry("PUCALA", "PUCALÁ"),
        Map.entry("TUMAN", "TUMÁN"),
        Map.entry("ILLIMO", "ÍLLIMO"),
        Map.entry("MOCHUMI", "MOCHUMÍ"),
        Map.entry("MORROPE", "MÓRROPE"),
        Map.entry("TUCUME", "TÚCUME"),
        Map.entry("SAN BARTOLOME", "SAN BARTOLOMÉ"),
        Map.entry("SAN DAMIAN", "SAN DAMIÁN"),
        Map.entry("SANTA MARIA", "SANTA MARÍA"),
        Map.entry("ANCON", "ANCÓN"),
        Map.entry("JESUS MARIA", "JESÚS MARÍA"),
        Map.entry("LURIN", "LURÍN"),
        Map.entry("PACHACAMAC", "PACHACÁMAC"),
        Map.entry("RIMAC", "RÍMAC"),
        Map.entry("SANTA MARIA DEL MAR", "SANTA MARÍA DEL MAR"),
        Map.entry("VILLA MARIA DEL TRIUNFO", "VILLA MARÍA DEL TRIUNFO"),
        Map.entry("SAN JOAQUIN", "SAN JOAQUÍN"),
        Map.entry("TENIENTE CESAR LOPEZ ROJAS", "TENIENTE CÉSAR LÓPEZ ROJAS"),
        Map.entry("PADRE MARQUEZ", "PADRE MÁRQUEZ"),
        Map.entry("IÑAPARI", "IÑAPARÍ"),
        Map.entry("TAHUAMANU", "TAHUAMANÚ"),
        Map.entry("CHACAYAN", "CHACAYÁN"),
        Map.entry("CONSTITUCION", "CONSTITUCIÓN"),
        Map.entry("PUERTO BERMUDEZ", "PUERTO BERMÚDEZ"),
        Map.entry("HUACHON", "HUACHÓN"),
        Map.entry("SAN FRANCISCO DE ASIS DE YARUSYACAN", "SAN FRANCISCO DE ASÍS DE YARUSYACÁN"),
        Map.entry("SIMON BOLIVAR", "SIMÓN BOLÍVAR"),
        Map.entry("TICLACAYAN", "TICLACAYÁN"),
        Map.entry("FRIAS", "FRÍAS"),
        Map.entry("JILILI", "JILILÍ"),
        Map.entry("COLAN", "COLÁN"),
        Map.entry("EL TALLAN", "EL TALLÁN"),
        Map.entry("VEINTISEIS DE OCTUBRE", "VEINTISÉIS DE OCTUBRE"),
        Map.entry("LOS ORGANOS", "LOS ÓRGANOS"),
        Map.entry("MANCORA", "MÁNCORA"),
        Map.entry("AZANGARO", "AZÁNGARO"),
        Map.entry("SAN GABAN", "SAN GABÁN"),
        Map.entry("EL ESLABON", "EL ESLABÓN"),
        Map.entry("YANTALO", "YANTALÓ"),
        Map.entry("SAN HILARION", "SAN HILARIÓN"),
        Map.entry("ELIAS SOPLIN VARGAS", "ELÍAS SOPLÍN VARGAS"),
        Map.entry("POLVORA", "PÓLVORA"),
        Map.entry("CORONEL GREGORIO ALBARRACIN LANCHIPA", "CORONEL GREGORIO ALBARRACÍN LANCHIPA"),
        Map.entry("INCLAN", "INCLÁN"),
        Map.entry("HEROES ALBARRACIN", "HÉROES ALBARRACÍN"),
        Map.entry("YURUA", "YURÚA"),
        Map.entry("IPARIA", "IPARÍA"),
        Map.entry("CURIMANA", "CURIMANÁ"),
        Map.entry("PURUS", "PURÚS"),
        Map.entry("ANTILLAS HOLANDESAS", "REINO DE LOS PAÍSES BAJOS"),
        Map.entry("TRINIDAD TOBAGO", "TRINIDAD Y TOBAGO"),
        Map.entry("QATAR", "CATAR"),
        Map.entry("SEATLE", "SEATTLE"),
        Map.entry("BEIJING (PEKIN)", "PEKÍN (BEIJING)"),
        Map.entry("FRANKFURT", "FRÁNCFORT"),
        Map.entry("KHARKOV", "JÁRKOV"),
        Map.entry("JAKARTA", "YAKARTA"),
        Map.entry("AL - KUWAIT", "AL  KUWAIT"),
        Map.entry("GUANGZHOU", "CANTÓN"),
        Map.entry("SKOPJE", "SKOPIE"),
        Map.entry("HOLANDA", "PAÍSES BAJOS"),
        Map.entry("RIO DE JANEIRO", "RÍO DE JANEIRO")
    );

    public static String corregirNombre(String nombre) {
        if (nombre == null || nombre.isBlank()) { return nombre; }
        return nombresConTilde.getOrDefault(nombre, nombre);
    }
}