
server.port=8080
server.servlet.context-path=${APPLICATION_ROOT}
server.error.whitelabel.enabled=false

spring.servlet.multipart.max-file-size=8MB
spring.servlet.multipart.max-request-size=8MB

spring.data.mongodb.uri=mongodb://${MONGO_USER_P}:${MONGO_PASS_P}@${MONGO_HOST_P}:${MONGO_PORT_P}/${MONGO_DB_P}?authSource=${MONGO_DB_SOURCE}&replicaSet=rs0&tls=true

application.title = Administrador CRON de Presentacion de resultados
application.version = 2.0

# ======================================
# BASE DE DATOS DE PRESENTACION DE RESULTADOS
# ======================================
spring.data.mongodb.secondary.uri = mongodb://${MONGO_USER_S}:${MONGO_PASS_S}@${MONGO_HOST_S}:${MONGO_PORT_S}?authSource=${MONGO_DB_SOURCE}&replicaSet=rs0&tls=true
spring.data.mongodb.secondary.database = ${MONGO_DB_S}

server.error.include-message=always

logging.level.root=DEBUG
logging.level.pe.gob.onpe.pradminbackend=DEBUG
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.amqp=DEBUG

app.sce-batch-pr.transmision.send-queue=requestpr.queue
app.sce-batch-pr.transmision.reply-queue=responsepr.queue

app.sce-batch-pr.transmision.send-queue-file=requestpr.queue.file
app.sce-batch-pr.transmision.reply-queue-file=responsepr.queue.file

security.jwt.tokenExpirationTime=300
security.jwt.refreshTokenExpTime=600
security.jwt.tokenIssuer=ONPE
security.jwt.tokenSigningKey=${JWT_SECRET}

# ========================================
# CIUDADANO CRON
# ========================================
tiempo.programacion.bd=${TIEMPO_PROGRAMACION_BD}

# ======================================
# ADMIN CIUDADANO BACKEND
# ======================================
admin.ciudadano.backend.url=${ADMIN_CIUDADANO_BACKEND}

