
server.port=8080
server.servlet.context-path=${APPLICATION_ROOT}
server.error.whitelabel.enabled=false

spring.servlet.multipart.max-file-size=8MB
spring.servlet.multipart.max-request-size=8MB

spring.data.mongodb.uri=mongodb://${MONGO_USER_P}:${MONGO_PASS_P}@${MONGO_HOST_P}:${MONGO_PORT_P}/${MONGO_DB_P}?authSource=${MONGO_DB_SOURCE}&replicaSet=rs0&tls=true

# ======================================
# BASE DE DATOS DE PRESENTACION DE RESULTADOS
# ======================================
spring.data.mongodb.secondary.uri = mongodb://${MONGO_USER_S}:${MONGO_PASS_S}@${MONGO_HOST_S}:${MONGO_PORT_S}?authSource=${MONGO_DB_SOURCE}&replicaSet=rs0&tls=true
spring.data.mongodb.secondary.database = ${MONGO_DB_S}

springdoc.api-docs.enabled = true
springdoc.swagger-ui.enabled = true
springdoc.swagger-ui.path = /swagger-ui.html
application.title = Administrador de Presentacion de resultados
application.version = 2.4

sce.nacion.url=${SCE_NACION_URL}

server.error.include-message=always

logging.level.root=DEBUG
logging.level.pe.gob.onpe.pradminbackend=DEBUG
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.amqp=DEBUG

pr.nfs.path=${PR_NFS_PATH}
pr.nfs.files=${PR_NFS_FILES}

spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}


app.sce-batch-pr.transmision.send-queue=requestpr.queue
app.sce-batch-pr.transmision.reply-queue=responsepr.queue

app.sce-batch-pr.transmision.send-queue-file=requestpr.queue.file
app.sce-batch-pr.transmision.reply-queue-file=responsepr.queue.file


sasa.url=${SASA_URL}
sasa.codigo=PR
security.jwt.tokenExpirationTime=300
security.jwt.refreshTokenExpTime=600
security.jwt.tokenIssuer=ONPE
security.jwt.tokenSigningKey=${JWT_SECRET}

recaptcha.siteKey=${RECAPTCHA_SITE_KEY}
recaptcha.secretKey=${RECAPTCHA_SECRET_KEY}
recaptcha.threshold=${RECAPTCHA_THRESHOLD}
recaptcha.validar=${RECAPTCHA_VALIDAR}
seguridad.validar=${SEGURIDAD_VALIDAR}
crossorigin.habilitado=${CROSSORIGIN_HABILITADO}
crossorigin.urls=${URL_PR_ADMIN}

public.key=${PUBLIC_KEY}
private.key=${PRIVATE_KEY}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.database=0
spring.data.redis.ssl.enabled=${REDIS_SSL_ENABLED}
spring.data.redis.timeout=${REDIS_TIMEOUT}

# ======================================
# CONSULTA OP BACKEND
# ======================================
cop.backend.url=${COP_BACKEND_URL}

# ======================================
# BOLETINES BACKEND
# ======================================
boletines.backend.url=${BOLETINES_BACKEND_URL}

# ========================================
# CIUDADANO CRON
# ========================================
##CONSULTA OP BACKEND EXCEL
app.consulta.backend = ${COP_BACKEND_EXCEL}

pr_admin_access_key=${PR_ADMIN_ACCESS_KEY}

aws.region=${AWS_REGION}
aws.bucket-name=${AWS_BUCKET_NAME}
aws.s3.key-actas-prefix=${AWS_S3_KEY_ACTAS_PREFIX}

despliegue-nube=${DESPLIEGUE_NUBE}
admin-nube-backend-url=${ADMIN_NUBE_BACKEND_URL}
