package pe.gob.onpe.presentacionbackend.model.bd.service;

import java.util.List;

import pe.gob.onpe.presentacionbackend.model.bd.documents.VwPrSenadoresDistritoElectoralMultiple;
import pe.gob.onpe.presentacionbackend.model.dto.senadoresdistritomultiple.OrganizacionPoliticaDto;
import pe.gob.onpe.presentacionbackend.model.dto.senadoresdistritomultiple.RequestParticipanteCandidatoOrganizacionSenadorDistritoMultipleDto;
import pe.gob.onpe.presentacionbackend.model.dto.senadoresdistritomultiple.RequestParticipanteCandidatoSenadorDistritoMultipleDto;
import pe.gob.onpe.presentacionbackend.model.dto.senadoresdistritomultiple.RequestParticipanteSenadorDistritoMultipleDto;
import pe.gob.onpe.presentacionbackend.model.dto.senadoresdistritomultiple.ResponseParticipanteCandidatoSenadorDistritoMultipleDto;
import pe.gob.onpe.presentacionbackend.model.dto.senadoresdistritomultiple.ResponseParticipanteSenadorDistritoMultipleDto;

public interface VwPrSenadoresDistritoElectoralMultipleService extends CrudService<VwPrSenadoresDistritoElectoralMultiple> {
	List<ResponseParticipanteSenadorDistritoMultipleDto> listaParticipantesUbicacionGeograficaNombre(RequestParticipanteSenadorDistritoMultipleDto filtroParticipanteDto);
	List<ResponseParticipanteCandidatoSenadorDistritoMultipleDto> listaParticipantesCandidato(RequestParticipanteCandidatoSenadorDistritoMultipleDto filtroParticipanteCandidatoDto);
	List<ResponseParticipanteCandidatoSenadorDistritoMultipleDto> listaParticipantesCandidatoOrganizacion(RequestParticipanteCandidatoOrganizacionSenadorDistritoMultipleDto filtroParticipanteCandidatoNombreDto);
	List<OrganizacionPoliticaDto> listarOrganizacionPolitica(RequestParticipanteSenadorDistritoMultipleDto filtroParticipanteDto);

}